export const newsMockData = {
  status: "ok",
  page: 1,
  category: [
    "regional",
    "technology",
    "lifestyle",
    "business",
    "general",
    "programming",
    "science",
    "entertainment",
    "world",
    "sports",
    "finance",
    "academia",
    "politics",
    "health",
    "opinion",
    "food",
    "game",
    "fashion",
    "academic",
    "crap",
    "travel",
    "culture",
    "economy",
    "environment",
    "art",
    "music",
    "notsure",
    "CS",
    "education",
    "redundant",
    "television",
    "commodity",
    "movie",
    "entrepreneur",
    "review",
    "auto",
    "energy",
    "celebrity",
    "medical",
    "gadgets",
    "design",
    "EE",
    "security",
    "mobile",
    "estate",
    "funny",
  ],
  news: [
    {
      id: "1",
      title: "Заголовок новости 1",
      description: "Это краткое описание первой новости.",
      url: "https://example.com/news/1",
      author: "Иван Иванов",
      image: "https://example.com/images/news1.jpg",
      language: "en",
      category: ["security"],
      published: "2025-04-10 01:56:03 +0000",
    },
    {
      id: "2",
      title: "Заголовок новости 2",
      description: "Краткое описание второй новости.",
      url: "https://example.com/news/2",
      author: "Мария Петрова",
      image: "https://example.com/images/news2.jpg",
      language: "en",
      category: ["food"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "3",
      title: "Заголовок новости 3",
      description: "Краткое описание 3 новости.",
      url: "https://example.com/news/3",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["design"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "4",
      title: "Заголовок новости 4",
      description: "Краткое описание 4 новости.",
      url: "https://example.com/news/3",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["food"],
      published: "2025-04-10 03:15:30 +0000",
    },
    {
      id: "5",
      title: "Заголовок новости 5",
      description: "Краткое описание 5 новости.",
      url: "https://example.com/news/5",
      author: "Мария Гусева",
      image: "https://example.com/images/news5.jpg",
      language: "en",
      category: ["game"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "6",
      title: "Заголовок новости 6",
      description: "Краткое описание 6 новости.",
      url: "https://example.com/news/6",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["food"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "7",
      title: "Заголовок новости 7",
      description: "Краткое описание 7 новости.",
      url: "https://example.com/news/7",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["game"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "8",
      title: "Заголовок новости 8",
      description: "Краткое описание 8 новости.",
      url: "https://example.com/news/8",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["game"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "9",
      title: "Заголовок новости 9",
      description: "Краткое описание 9 новости.",
      url: "https://example.com/news/3",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["game"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "10",
      title: "Заголовок новости 10",
      description: "Краткое описание 10 новости.",
      url: "https://example.com/news/10",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["game"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "11",
      title: "Заголовок новости 11",
      description: "Краткое описание 11 новости.",
      url: "https://example.com/news/11",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["game"],
      published: "2025-04-10 04:15:30 +0000",
    },
  ],
};
