export const newsMockData = {
  status: "ok",
  page: 1,
  news: [
    {
      id: "1",
      title: "Заголовок новости 1",
      description: "Это краткое описание первой новости.",
      url: "https://example.com/news/1",
      author: "Иван Иванов",
      image: "https://example.com/images/news1.jpg",
      language: "en",
      category: ["Политика"],
      published: "2025-04-10 01:56:03 +0000",
    },
    {
      id: "2",
      title: "Заголовок новости 2",
      description: "Краткое описание второй новости.",
      url: "https://example.com/news/2",
      author: "Мария Петрова",
      image: "https://example.com/images/news2.jpg",
      language: "en",
      category: ["Экономика"],
      published: "2025-04-10 04:15:30 +0000",
    },
    {
      id: "3",
      title: "Заголовок новости 3",
      description: "Краткое описание 3 новости.",
      url: "https://example.com/news/3",
      author: "Мария Гусева",
      image: "https://example.com/images/news3.jpg",
      language: "en",
      category: ["Экономика"],
      published: "2025-04-10 04:15:30 +0000",
    },
  ],
};
